[project]
name = "gobcas"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "flask==2.0.1",
    "flask-cas-ng==1.1.0",
    "prettyconf>=2.3.0",
    "werkzeug==2.2.2",
]

[dependency-groups]
dev = ["ipython>=9.2.0", "pytest>=8.3.5"]

prod = []
